# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharApp',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('char_name', models.CharField(max_length=80, verbose_name='Character Name')),
                ('date_applied', models.DateTimeField(verbose_name='Date Applied')),
                ('background', models.TextField(verbose_name='Background')),
                ('account_id', models.IntegerField(default=1, verbose_name='Account ID')),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
